version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 120
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_WARN_ON_HEAD_FAILURE: never

  coti-node:
    container_name: coti-node
    image: 'atomnode/coti-node:${VERSION:-latest}'
    command: /bin/bash -c "./update-env && java -Xmx8g -jar fullnode/target/fullnode-*.RELEASE.jar --spring.config.additional-location=./data/fullnode.properties"
    ports:
      - '7070:7070'
    expose:
      - 80
      - 7070
    restart: on-failure
    env_file:
      - .env
    volumes:
      - './data:/app/data'
      - './rocksdb:/app/FullNoderocksDB1'
    environment:
      VIRTUAL_HOST: ${SERVERNAME}
      VIRTUAL_PORT: 7070
      LETSENCRYPT_HOST: ${SERVERNAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
    depends_on:
      - nginx
      - dockergen
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 8G
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    logging:
      driver: 'json-file'
      options:
        max-file: 5
        max-size: 50m

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'
    logging:
      driver: 'json-file'
      options:
        max-file: 5
        max-size: 50m

  dockergen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx
      - dockergen
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
