version: '3'

networks:
  default:
    name: gateway
    external: true
    driver: bridge

volumes:
  coti_config:
  coti_db:
  letsencrypt:

services:
  coti-node:
    container_name: coti-node
    image: 'atomnode/coti-node:${VERSION:-latest}'
    # image: 'containous/whoami' # Debug
    command: /bin/bash -c "./create-properties && java -Xmx8g -jar fullnode/target/fullnode-*.RELEASE.jar --spring.config.additional-location=./data/fullnode.properties"
    ports:
      - '7070:7070'
      # - '7070:80' # Debug
    expose:
      - 7070
      - 80
    env_file:
      - .env
    volumes:
      - 'coti_config:/app/data'
      - 'coti_db:/app/${DATABSE_FOLDER_NAME:-FullNoderocksDB}'
    labels:
      # SSL redirect requires a separate router (https://github.com/containous/traefik/issues/4688#issuecomment-477800500)
      - 'traefik.http.routers.coti-node.entryPoints=port7070'
      - 'traefik.http.routers.coti-node.rule=host(`${SERVERNAME}`)'
      - 'traefik.http.middlewares.coti-node-redirect.redirectScheme.scheme=https'
      - 'traefik.http.middlewares.coti-node-redirect.redirectScheme.permanent=true'
      - 'traefik.http.routers.coti-node.middlewares=coti-node-redirect'
      # SSL endpoint
      - 'traefik.http.routers.coti-node-ssl.entryPoints=port443'
      - 'traefik.http.routers.coti-node-ssl.rule=host(`${SERVERNAME}`)'
      - 'traefik.http.routers.coti-node-ssl.tls=true'
      - 'traefik.http.routers.coti-node-ssl.tls.certResolver=le-ssl'
      - 'traefik.http.routers.coti-node-ssl.service=coti-node-ssl'
      - 'traefik.http.services.coti-node-ssl.loadBalancer.server.port=7070'
      # - 'traefik.http.services.coti-node-ssl.loadBalancer.server.port=80' # Debug
      - 'traefik.http.routers.coti-node-ssl.middlewares=securedheaders@docker' # Enable http middleware for A+ SSL
    logging:
      options:
        max-size: "50m"
        max-file: "3"


  traefik:
    container_name: traefik
    image: traefik:2.6
    ports:
      - '80:80'
      - '443:443'
    command:
      - '--global.sendAnonymousUsage=false'
      - '--log.level=INFO'
      - '--api'
      - '--metrics'
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.buckets=0.1,0.3,1.2,5.0'
      - '--providers.docker=true'
      - '--providers.docker.watch'

      - '--entryPoints.port443.address=:443'
      - '--entryPoints.port80.address=:80'
      - '--entryPoints.port7070.address=:7070'

      - '--certificatesResolvers.le-ssl.acme.tlsChallenge=true'
      - '--certificatesResolvers.le-ssl.acme.email=${EMAIL}'
      - '--certificatesResolvers.le-ssl.acme.storage=/letsencrypt/acme.json'

      - "--providers.file.filename=/traefik_conf.yml" # SSL A+ (https://www.simplecto.com/improve-traefik-https-encryption-qualys-ssl-labs-testssl-sh/)
    labels:
      # HSTS https://www.anselms.net/blog/traefik-ssllabs.html
      traefik.http.middlewares.securedheaders.headers.forcestsheader: "true"
      traefik.http.middlewares.securedheaders.headers.sslRedirect: "true"
      traefik.http.middlewares.securedheaders.headers.STSPreload: "true"
      traefik.http.middlewares.securedheaders.headers.ContentTypeNosniff: "true"
      traefik.http.middlewares.securedheaders.headers.BrowserXssFilter: "true"
      traefik.http.middlewares.securedheaders.headers.STSIncludeSubdomains: "true"
      traefik.http.middlewares.securedheaders.headers.STSSeconds: "315360000"
    volumes:
      - letsencrypt:/letsencrypt/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_conf.yml:/traefik_conf.yml # SSL A+ (https://www.simplecto.com/improve-traefik-https-encryption-qualys-ssl-labs-testssl-sh/)
    networks:
      - default
    logging:
      options:
        max-size: "50m"
        max-file: "3"
